### ISSUE TITLE
Document new downstream jobs

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#361]
Start once packit/packit-service#55 and packit/packit-service#74 is implemented.

* [x] Provide docs for the new jobs. (#403)
* [x] Create a blog post with some screenshots of the real jobs. (#404)
* [x] Make sure to cover https://github.com/packit/packit-service/issues/1310
